language: go
sudo: false
install: true
os:
  - linux
  - osx
go:
  - 1.5.4
  - 1.6.3
  - 1.7rc5
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  matrix:
    - GOARCH=amd64
    - GOARCH=386
script:
  - go test -x
