language: go
sudo: false
go:
  - 1.4.3
  - 1.5.2
  - 1.6beta1
  - tip
env:
  - GOARCH=amd64
  - GOARCH=386
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - go get github.com/tools/godep
  - go get -x -t -d
  - godep restore
script:
  - go test -x
